# Generated by Django 4.2 on 2023-10-05 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ads_run", models.PositiveIntegerField()),
                ("actual_spend", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost_sharing", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reimbursement", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ad_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ad_manager.adtype",
                    ),
                ),
            ],
        ),
    ]
