# Generated by Django 4.2 on 2023-10-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adrecord",
            name="ad_type",
            field=models.CharField(max_length=10),
        ),
    ]
