# Generated by Django 4.2 on 2023-10-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_manager", "0002_alter_adrecord_ad_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adrecord",
            name="reimbursement",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
